### ISSUE TITLE
Activate Coveralls

### ISSUE THREAD

**Issue by helgee** [JuliaTime/LeapSeconds.jl#1]

**Comment by omus** [comment]
I'll note Codecov is already enabled for the repo: https://codecov.io/gh/JuliaTime/LeapSeconds.jl

**Comment by omus** [comment]
Do you want Coveralls in addition?

**Comment by helgee** [comment]
I have mindlessly added Coveralls as well as Codecov to all my projects because they are both in the standard Julia package template. But I think you are right that one is enough.
