### ISSUE TITLE
Publish!

### ISSUE THREAD

**Issue by helgee** [JuliaTime/LeapSeconds.jl#2]
@omus and @giordano can I get a quick review before I push the button?

@omus Is attobot configured for the repo?

**Comment by omus** [comment]
I glanced over the code and it looks reasonable.

For a future version of this I'm hoping to get this setup like TimeZones.jl so you can use the latest leap second data without requiring a new release. Now that this is an independent package that should be easier to do :)

**Comment by omus** [comment]
Attobot should be configured and ready to go

**Comment by helgee** [comment]
I have tagged a release. Thanks @omus!
